name: Helix Core

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    paths:
      - 'core/**'
      - '.github/workflows/build-core.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'core/**'
      - '.github/workflows/build-core.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}
  # P4D version
  MAJOR_VERSION: 2021
  MINOR_VERSION: 2
  PATCH_VERSION: 2220431

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/core

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./core/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}-${{ env.PATCH_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MAJOR_VERSION=${{ env.MAJOR_VERSION }}
            MINOR_VERSION=${{ env.MINOR_VERSION }}
            PATCH_VERSION=${{ env.PATCH_VERSION }}
